channels:
  - pytorch
  - nvidia
  - conda-forge
  - dglteam/label/cu117
dependencies:
  - python
  - pytorch-cuda=11.7
  - pytorch
  - rdkit
  - dgl
  - openmm
  - openmmtools
  - matplotlib
  - h5py