channels:
  - pytorch
  - nvidia
  - conda-forge
  - dglteam/label/cu117
  - psi4
dependencies:
  - python
  - pytorch-cuda=11.7
  - pytorch
  - qcportal
  - rdkit
  - dgl
  - openmm
  - openmmtools
  - matplotlib
  - ase
  - mdtraj
  - nglview
  - psi4
  - pip
  - pip:
    - pytorch-warmup