[build-system]
requires = ["setuptools"
]
build-backend = "setuptools.build_meta"

[project]
name = "grappa"
version = "1.3.0"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where=["src"]


[project.scripts]
grappa_eval = "grappa.training.eval_model:grappa_eval"
grappa_export = "grappa.training.export_model:grappa_export"
grappa_release = "grappa.training.export_model:grappa_release"
grappa_gmx = "grappa.wrappers.gromacs_wrapper:main"