[build-system]
requires = ["setuptools"
]
build-backend = "setuptools.build_meta"

[project]
name = "grappa"
version = "0.1.0"
dependencies = [
    "numpy",
    "dgl",
    "torch",
    "openmm",
    "rdkit",
    "matplotlib",
    "pyyaml",
]

[project.scripts]
grappa_train = "grappa.run.client:run_client"
grappa_full_run = "grappa.run.client:full_run"
grappa_eval = "grappa.run.eval:eval_client"
grappa_compare = "grappa.run.compare:client"

[tool.setuptools]
include-package-data = true
# This is already the default behaviour if your are using
# pyproject.toml to configure your build.
# You can deactivate that with `include-package-data = false`

[tool.setuptools.packages.find]
where=["src"]
