[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "grappa-ff"
version = "1.3.0"
authors = [
    { name="Leif Seute", email="leif.seute@h-its.org" }
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "numpy<=1.26.4",
    "pandas",
    "scipy",
    "pyyaml",
    "pydantic",
    "seaborn",
    "tqdm",
    "matplotlib",
    "rdkit",
    "wandb",
    "networkx",
    "charset-normalizer",
    "hydra-core",
    "torch",
    "dgl",
    "torchdata",
    "lightning>=2.3.3"
]
requires-python = ">=3.10"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where=["src"]


[project.scripts]
grappa_gmx = "grappa.wrappers.gromacs_wrapper:main"
grappa_export = "grappa.training.export_model:grappa_export"
