defaults:
  - _self_

ckpt_path: models/grappa-1.3.0/checkpoint.ckpt
n_bootstrap: 100
test_data_path: null
accelerator: 'gpu'
plot: false

classical_force_fields: []

datasets: null
pure_test_datasets: []
ff_lookup: {}

gradient_contributions:
- bond
- angle
- proper
- improper
- nonbonded
- total

compare_forcefields: []

eval_model: true

grappa_contributions: null