defaults:
  - default
  - _self_

ckpt_path: models/grappa-1.3.0/checkpoint.ckpt
n_bootstrap: 1
accelerator: 'gpu'
plot: false

classical_force_fields:
  - grappa-1.3_tabulated

datasets:
  - dipeptides-300K-grappa-tabulated
pure_test_datasets: []
ff_lookup:
  dipeptides-300K-grappa-tabulated: grappa-1.3_tabulated

gradient_contributions:
- bond
- angle
- proper
- improper
- nonbonded
- total

compare_forcefields: [['','grappa-1.3_tabulated']]
