defaults:
  - default
  - _self_

ckpt_path: models/grappa-1.3.0/checkpoint.ckpt
# n_bootstrap: 1000
n_bootstrap: 1
accelerator: 'gpu'
plot: true

classical_force_fields: []
datasets: [dipeptides-300K-amber99]
pure_test_datasets: []

gradient_contributions:
- bond
- angle
- proper
- improper
- nonbonded
- total

compare_forcefields: []

ff_lookup:
  dipeptides-300K-amber99: amber99sbildn

grappa_contributions:
- proper
- improper