defaults:
  - default
  - _self_

ckpt_path: models/grappa-1.3.0/checkpoint.ckpt
n_bootstrap: 1
test_data_path: null
accelerator: 'gpu'
plot: true

classical_force_fields:
  - amber99sbildn
  - grappa-1.3
  - grappa-1.3-tabulated

datasets:
  - dipeptides-300K-grappa-1.3
pure_test_datasets: []
ff_lookup:
  dipeptides-300K-grappa-1.3: grappa-1.3

gradient_contributions:
- bond
- angle
- proper
- improper
- nonbonded
- total

compare_forcefields:
  - ['amber99sbildn', 'grappa-1.3']
  - ['amber99sbildn', 'grappa-1.3-tabulated']
  - ['grappa-1.3', 'grappa-1.3-tabulated']

eval_model: false