defaults:
  - default
  - _self_

ckpt_path: models/grappa-1.3.0/checkpoint.ckpt
n_bootstrap: 1000
test_data_path: models/grappa-1.3.0/noisy_charges
accelerator: 'gpu'
plot: true

classical_force_fields: []
datasets: [dipeptides-300K-amber99, dipeptides-300K-noise-0-05, dipeptides-300K-noise-0-1, dipeptides-300K-noise-0-3]
pure_test_datasets: []

compare_forcefields: []

ff_lookup:
  dipeptides-300K-amber99: amber99sbildn