data:
  data_module:
    balance_factor: 0.0
    conf_strategy: 32
    datasets:
    - spice-des-monomers
    - spice-pubchem
    - gen2
    - gen2-torsion
    - rna-diverse
    - pepconf-dlc
    - protein-torsion
    - spice-dipeptide
    - dipeptides-300K-openff-1.2.0
    - dipeptides-300K-amber99
    - dipeptides-300K-charmm36_nonb
    - dipeptides-1000K-openff-1.2.0
    - dipeptides-1000K-amber99
    - dipeptides-1000K-charmm36_nonb
    - uncapped-300K-openff-1.2.0
    - uncapped-300K-amber99
    - dipeptides-hyp-dop-300K-amber99
    - dipeptides-radical-300K
    - bondbreak-radical-peptides-300K
    ff_lookup: {}
    partition:
    - 0.8
    - 0.1
    - 0.1
    pin_memory: true
    pure_test_datasets:
    - rna-trinucleotide
    pure_train_datasets:
    - rna-nucleoside
    pure_val_datasets: []
    ref_terms:
    - nonbonded
    seed: 0
    split_path: /local/user/seutelf/grappa/models/grappa-1.3.0/split.json
    splitpath: espaloma_split
    test_loader_workers: 4
    tr_subsampling_factor: null
    train_batch_size: 32
    train_loader_workers: 4
    val_batch_size: 32
    val_conf_strategy: 200
    val_loader_workers: 4
    weights:
      rna-diverse: 3
      rna-nucleoside: 5
      spice-pubchem: 0.8
  energy:
    gradients: true
    terms:
    - bond
    - angle
    - proper
    - improper
experiment:
  checkpointer:
    auto_insert_metric_name: false
    dirpath: ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    every_n_epochs: 5
    filename: epoch:{epoch}-early_stop_loss:{early_stopping_loss:.2f}
    mode: min
    monitor: early_stopping_loss
    save_last: true
    save_top_k: 2
  ckpt_cfg_override: false
  ckpt_path: null
  evaluation:
    n_bootstrap: 1000
  progress_bar: true
  train:
    early_stopping_energy_weight: 3.0
    energy_weight: 1.0
    gradient_weight: 0.8
    improper_regularisation: 0.001
    lr: 1.5e-05
    lr_decay: 0.8
    param_loss_epochs: 100
    param_weight: 0.001
    patience: 50
    proper_regularisation: 0.001
    start_qm_epochs: 2
    time_limit: 47.5
    tuplewise_weight: 0.0
    warmup_steps: 500
    weight_decay: 0
  trainer:
    accelerator: gpu
    check_val_every_n_epoch: 1
    deterministic: false
    log_every_n_steps: 10
    max_epochs: 2000
    min_epochs: 5
    overfit_batches: 0
  wandb:
    name: published
    project: grappa-1.3
    save_code: true
    tags: []
model:
  gated_torsion: true
  gnn_attention_heads: 16
  gnn_attentional_layers: 7
  gnn_convolutions: 0
  gnn_dropout_attention: 0.3
  gnn_dropout_conv: 0.0
  gnn_dropout_final: 0.1
  gnn_dropout_initial: 0.0
  gnn_width: 512
  graph_node_features: 256
  harmonic_gate: false
  in_feat_dims: {}
  in_feat_name:
  - atomic_number
  - ring_encoding
  - partial_charge
  - degree
  in_feats: null
  layer_norm: true
  learnable_statistics: false
  n_periodicity_improper: 2
  n_periodicity_proper: 3
  only_n2_improper: true
  positional_encoding: true
  self_interaction: true
  shifted_elu: true
  stat_scaling: true
  symmetric_transformer_depth: 1
  symmetric_transformer_dropout: 0.5
  symmetric_transformer_n_heads: 8
  symmetric_transformer_width: 512
  symmetriser_depth: 4
  symmetriser_width: 256
  torsion_cutoff: 0.0001
