channels:
  - pytorch
  - nvidia
  - conda-forge
  - dglteam/label/cu121
dependencies:
  - python=3.9
  - pytorch-cuda=12.1
  - pytorch=2.0.0
  - rdkit=2023.9.1
  - dgl
  - openmm=7.7.0=py39hb10b54c_0
  - matplotlib
  - numpy
  - pandas
  - pytorch-lightning=2.1.0
  - wandb=0.16.1
  - networkx=3.2.1