channels:
  - conda-forge
  - omnia
  - dglteam/label/cu117
  - pytorch
dependencies:
  - python=3.6
  - rdkit
  - openmm
  - openmmtools
  - openmmforcefields
  - matplotlib
  - ase
  - h5py
  - openff-toolkit
  - python
  - pytorch
  - dgl
  - pip