defaults:
  - _self_

ckpt_path: /local/user/seutelf/grappa/ckpt/grappa/baseline/2024-06-26_10-13-48/last.ckpt
n_bootstrap: 1000
test_data_path: null
accelerator: 'gpu'
classical_force_fields:
  - amber99sbildn
  - openff-1.2.0
  - amber14
  - gaff-2.11
  - reference_ff
test_datasets: []