defaults:
  - _self_

ckpt_path: /local/user/seutelf/grappa/ckpt/grappa-1.3/published/2024-06-26_01-30-36/epoch:789-early_stop_loss:19.65.ckpt
n_bootstrap: 1
test_data_path: null
accelerator: 'gpu'
plot: true

classical_force_fields:
  - amber99sbildn
  - gaff-2.11
  # - amber14
  # - openff-1.2.0
  # - reference_ff

datasets: null
pure_test_datasets: null
# datasets:
#   - uncapped-300K-amber99
# pure_test_datasets: []

gradient_contributions:
- bond
- angle
- proper
- improper
- nonbonded
- total

compare_forcefields:
  - ['amber99sbildn', '']
  - ['gaff-2.11', '']
  # - ['openff-1.2.0', '']
  # - ['amber14', '']
  # - ['reference_ff', '']