defaults:
  - train
  - _self_

experiment:
  ckpt_path: null
  wandb:
    name: example
    project: grappa
  progress_bar: true

model:
  in_feat_name:
    - atomic_number
    - ring_encoding
    - partial_charge
    - degree

data:
  datasets:
    - spice-dipeptide
  pure_test_datasets: []
  pure_val_datasets: []
  pure_train_datasets: []
  splitpath: espaloma_split
  ref_terms:
    - nonbonded
  seed: 0

energy:
  terms:
    - bond
    - angle
    - proper
    - improper