defaults:
  - train
  - _self_

experiment:
  ckpt_path: null
  wandb:
    name: baseline
    project: grappa-1.3
  progress_bar: true

model:
  in_feat_name:
    - atomic_number
    - ring_encoding
    - partial_charge
    - degree

data:
  datasets:
    - spice-des-monomers
    - spice-pubchem
    - gen2
    - gen2-torsion
    - rna-diverse
    - pepconf-dlc
    - protein-torsion
    - spice-dipeptide
    - dipeptides-300K-openff-1.2.0
    - dipeptides-300K-amber99
    - dipeptides-300K-charmm36
    - dipeptides-1000K-openff-1.2.0
    - dipeptides-1000K-amber99
    - dipeptides-1000K-charmm36
    - uncapped-300K-openff-1.2.0
    - uncapped-300K-amber99
    - dipeptides-hyp-dop-300K-amber99
    - dipeptides-radical-300K
    - bondbreak-radical-peptides-300K

  pure_test_datasets:
    - rna-trinucleotide
  pure_val_datasets: []
  pure_train_datasets:
    - rna-nucleoside
  splitpath: espaloma_split
  partition: [0.8, 0.1, 0.1]
  ref_terms:
    - nonbonded
  seed: 0

energy:
  terms:
    - bond
    - angle
    - proper
    - improper