defaults:
  - train
  - _self_

experiment:
  ckpt_path: null
  wandb:
    name: amber99-angles
    project: grappa-1.3
  progress_bar: true
  evaluation:
    classical_force_fields: [amber99sbildn]

model:
  in_feat_name:
    - atomic_number
    - ring_encoding
    - partial_charge
    - degree
    # - charge_model

data:
  datasets:
    # - dipeptides-300K-am1BCC
    - dipeptides-300K-amber99
    # - dipeptides-300K-charmm
    # - dipeptides-1000K-am1BCC
    - dipeptides-1000K-amber99
    # - dipeptides-1000K-charmm
    # - uncapped-300K-am1BCC
    - uncapped-300K-amber99
    # - uncapped-300K-charmm
    # - dipeptides-hyp-dop-300K-amber99

  pure_test_datasets: []
  pure_val_datasets: []
  pure_train_datasets: []
  splitpath: espaloma_split #NOTE: replace by grappa-1.3 later
  partition: [0.8, 0.1, 0.1]
  ref_terms:
    - nonbonded
    - bond
    # - angle
    - proper
    - improper
  seed: 0

energy:
  terms:
    # - bond
    - angle
    # - proper
    # - improper