defaults:
  - train
  - _self_

experiment:
  ckpt_path: null
  wandb:
    name: baseline
    project: grappa-1.3
  progress_bar: true

model:
  in_feat_name:
    - atomic_number
    - ring_encoding
    - partial_charge
    - degree
    - charge_model

data:
  datasets:
    - spice-des-monomers
    - spice-pubchem
    - gen2
    - gen2-torsion
    - rna-diverse
    - spice-dipeptide
    - protein-torsion
    - pepconf-dlc
  pure_test_datasets:
    - rna-trinucleotide
  pure_val_datasets: []
  pure_train_datasets:
    - rna-nucleoside
  splitpath: espaloma_split
  partition: [0.8, 0.1, 0.1]
  ref_terms:
    - nonbonded
  seed: 0

energy:
  terms:
    - bond
    - angle
    - proper
    - improper